name: Build App CI

on:
    workflow_dispatch:
    push:
        branches: ['dev', 'feature/*']
    pull_request:
        branches: ['dev']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - run: pnpm ci
            - run: pnpm run build --if-present
            - uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/
